[book]
authors = ["Sam Mohr <samuel.mohr@hitachi-powergrids.com>", "Wojciech Polak <wojciech.polak@hitachi-powergrids.com>"]
language = "en"
multilingual = false
src = "docs"
title = "The Common Data Layer"

[build]
build-dir = "target/book"

[output.html]
git-repository-url = "https://github.com/epiphany-platform/CommonDataLayer"

[output.linkcheck]
warning-policy = "error"

[preprocessor.plantuml]
