[package]
name = "data-router"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "data-router"
path = "src/main.rs"

[dependencies]
# Workspace
utils       = { path = "../utils" }
rpc         = { path = "../rpc" }

# Crates.io
anyhow      = "1.0"
async-trait = "0.1"
env_logger  = "0.8"
log         = "0.4"
lru-cache   = "0.1"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
structopt   = "0.3"
tokio       = { version = "0.2", features = ["macros"] }
url         = { version = "2.2", features = ["serde"] }
uuid        = { version = "0.8", features = ["v1", "serde"] }
